"""Build the fictional, public-safe estate used by the Explorer guides.

The generated estate is deliberately disposable.  It contains no source material
from the real MarkdownLLM estate and uses fixed commit dates for repeatable docs.
"""

from __future__ import annotations

import argparse
import os
import shutil
import stat
import subprocess
from pathlib import Path


MARKER = ".public-demo-estate"


def remove_readonly(function, path: str, _error) -> None:
    """Retry removal after clearing Git's occasional Windows read-only bit."""
    os.chmod(path, stat.S_IWRITE)
    function(path)


def write(root: Path, relative: str, content: str) -> None:
    target = root / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content.strip() + "\n", encoding="utf-8")


def git(root: Path, *arguments: str, when: str | None = None) -> None:
    environment = os.environ.copy()
    if when:
        environment["GIT_AUTHOR_DATE"] = when
        environment["GIT_COMMITTER_DATE"] = when
    subprocess.run(
        ["git", "-c", f"safe.directory={root}", *arguments],
        cwd=root,
        env=environment,
        check=True,
        capture_output=True,
        text=True,
    )


def initialise(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)
    git(root, "init", "--initial-branch", "main")
    git(root, "config", "user.name", "Northstar Studio")
    git(root, "config", "user.email", "hello@northstar.example")


def commit(root: Path, message: str, when: str) -> None:
    git(root, "add", "--all")
    git(root, "commit", "--message", message, when=when)


def build_substrate(root: Path) -> None:
    initialise(root)
    write(root, MARKER, "Generated by explorer/tools/build_public_demo_estate.py")
    write(root, ".gitignore", "domain/")
    write(
        root,
        "AGENTS.md",
        """
---
name: Northstar Studio
description: A fictional MarkdownLLM substrate for public demonstrations
version: 1.0.0
---

# Northstar Studio

Northstar is a small, fictional studio showing how a substrate connects a
domain estate. Every person, project and decision in this example is invented.

## The model

1. The **substrate** supplies the shared structure.
2. Each **domain** owns a clear area of work.
3. Markdown holds durable context; git records accepted change.

> Start at the estate, choose a domain, then follow its files, skills and memory.
""",
    )
    write(
        root,
        "README.md",
        """
# Welcome to Northstar

This fabricated estate is the public demonstration surface for MarkdownLLM Explorer.

| Domain | Purpose |
|---|---|
| Product Studio | Shape useful products from observed needs |
| Research Library | Turn sources into reusable evidence |
| Service Operations | Keep delivery calm, visible and repeatable |
""",
    )
    write(
        root,
        "skills/estate-orientation.skill.md",
        """
---
id: estate-orientation
type: skill
status: stable
version: 1.0
created: 2026-08-10
---

# Estate orientation

Help a new reader understand the whole before opening the parts.

- Name the substrate and domain estate.
- Explain what each domain owns in one sentence.
- Point to recent commits as evidence of movement.
""",
    )
    commit(root, "launch: establish the Northstar substrate", "2026-08-10T09:30:00+01:00")
    write(
        root,
        "things/insights/visibility-builds-trust.md",
        """
---
id: visibility-builds-trust
type: insight
status: active
version: 1.0
created: 2026-08-21
tags: [visibility, trust]
---

# Visibility builds trust

A domain becomes easier to trust when a reader can see its purpose, recent
movement and source material without first learning the tools that maintain it.
""",
    )
    commit(root, "insight: make the estate legible at first glance", "2026-08-21T14:15:00+01:00")


def build_product_studio(root: Path) -> None:
    initialise(root)
    write(root, ".markdownllm", "version: 1\nname: Product Studio")
    write(
        root,
        "AGENTS.md",
        """
---
name: Product Studio
description: Turns observed needs into calm, testable product decisions
version: 1.0.0
---

# Product Studio

The Product Studio keeps discovery, product decisions and learning connected.
Its work begins with a real need and ends with observable evidence.
""",
    )
    write(
        root,
        "skills/discovery-interview.skill.md",
        """
---
id: discovery-interview
type: skill
status: stable
version: 1.1
created: 2026-08-12
---

# Discovery interview

Use a short conversation to understand the need before discussing features.

## Listen for

- the moment the problem appears;
- what the person does today;
- the cost of the workaround; and
- the smallest change that would feel useful.

## Finish with evidence

| Capture | Useful form |
|---|---|
| Current state | A concrete example |
| Desired outcome | An observable difference |
| Open question | The next thing to test |

> Curiosity first. The interface comes later.
""",
    )
    write(
        root,
        "skills/prototype-review.skill.md",
        """
---
id: prototype-review
type: skill
status: evolving
version: 1.0
created: 2026-08-12
---

# Prototype review

Watch someone complete one real journey. Record where the interface helps,
where it hesitates and what the person expected to happen next.
""",
    )
    write(
        root,
        "things/decisions/show-the-whole-first.md",
        """
---
id: show-the-whole-first
type: decision
status: accepted
version: 1.0
created: 2026-08-12
tags: [navigation, clarity]
---

# Show the whole first

Start with a simple view of the estate, then let the reader move into detail.
This preserves context while keeping the first screen calm.
""",
    )
    commit(root, "start: connect discovery to product decisions", "2026-08-12T10:00:00+01:00")
    write(
        root,
        "things/insights/evidence-before-roadmap.md",
        """
---
id: evidence-before-roadmap
type: insight
status: active
version: 1.0
created: 2026-08-19
tags: [discovery, evidence]
linked_things:
  - id: discovery-interview
    relation: implements
  - id: show-the-whole-first
    relation: informs
---

# Evidence before roadmap

The useful unit of planning is not a feature request. It is a need paired with
enough evidence to decide what should happen next.

## What changed

The studio now records one observed example beside every proposed outcome.
That makes a later product decision easier to explain and revisit.
""",
    )
    commit(root, "learn: pair every outcome with observed evidence", "2026-08-19T16:40:00+01:00")
    write(
        root,
        "things/retrospectives/first-prototype.md",
        """
---
id: first-prototype-retrospective
type: retrospective
status: completed
version: 1.0
created: 2026-08-25
linked_things:
  - id: prototype-review
    relation: validates
  - id: evidence-before-roadmap
    relation: derived-from
  - id: keep-source-and-inference-apart
    relation: references
---

# First prototype retrospective

The first walkthrough confirmed that clear labels matter more than extra controls.
The next iteration keeps the shell quiet and makes source context persistent.
""",
    )
    commit(root, "review: keep the first journey quiet and legible", "2026-08-25T11:20:00+01:00")


def build_research_library(root: Path) -> None:
    initialise(root)
    write(root, ".markdownllm", "version: 1\nname: Research Library")
    write(
        root,
        "AGENTS.md",
        """
---
name: Research Library
description: Preserves useful evidence without losing its source
version: 1.0.0
---

# Research Library

The library turns scattered reading into traceable, reusable evidence.
""",
    )
    write(
        root,
        "skills/source-comparison.skill.md",
        """
---
id: source-comparison
type: skill
status: stable
version: 1.0
created: 2026-08-14
---

# Source comparison

Compare sources by question, evidence strength, date and disagreement.
Keep inference separate from what a source directly supports.
""",
    )
    write(
        root,
        "things/insights/small-signals-compound.md",
        """
---
id: small-signals-compound
type: insight
status: active
version: 1.0
created: 2026-08-14
---

# Small signals compound

Several modest observations can become decision-worthy when their provenance
is clear and they point in the same direction.
""",
    )
    commit(root, "catalogue: create a traceable research library", "2026-08-14T09:10:00+01:00")
    write(
        root,
        "things/decisions/keep-source-and-inference-apart.md",
        """
---
id: keep-source-and-inference-apart
type: decision
status: accepted
version: 1.0
created: 2026-08-23
---

# Keep source and inference apart

Every summary states which claims come from a source and which are the studio's
interpretation. This keeps later decisions reviewable.
""",
    )
    commit(root, "decide: separate sourced fact from interpretation", "2026-08-23T15:05:00+01:00")


def build_service_operations(root: Path) -> None:
    initialise(root)
    write(root, ".markdownllm", "version: 1\nname: Service Operations")
    write(
        root,
        "AGENTS.md",
        """
---
name: Service Operations
description: Makes reliable delivery visible and repeatable
version: 1.0.0
---

# Service Operations

This domain holds the small routines that keep a service calm and observable.
""",
    )
    write(
        root,
        "skills/release-check.skill.md",
        """
---
id: release-check
type: skill
status: stable
version: 1.0
created: 2026-08-16
---

# Release check

Confirm the change, the evidence, the recovery path and the person who owns
the final release judgement.
""",
    )
    write(
        root,
        "things/decisions/calm-release-window.md",
        """
---
id: calm-release-window
type: decision
status: accepted
version: 1.0
created: 2026-08-16
---

# Calm release window

Release when the team can observe the result and recover deliberately, not at
the end of a rushed day.
""",
    )
    commit(root, "operate: make release ownership visible", "2026-08-16T13:25:00+01:00")
    write(
        root,
        "things/insights/recovery-is-part-of-delivery.md",
        """
---
id: recovery-is-part-of-delivery
type: insight
status: active
version: 1.0
created: 2026-08-24
---

# Recovery is part of delivery

A release plan is incomplete until the team knows how it will recognise a
problem, pause safely and return to the last known-good state.
""",
    )
    commit(root, "learn: treat recovery as part of the release", "2026-08-24T10:45:00+01:00")


def build(output: Path) -> Path:
    output = output.resolve()
    if output.exists():
        if not (output / MARKER).is_file():
            raise SystemExit(f"Refusing to replace unmarked directory: {output}")
        shutil.rmtree(output, onerror=remove_readonly)
    build_substrate(output)
    domain_root = output / "domain"
    build_product_studio(domain_root / "Product Studio")
    build_research_library(domain_root / "Research Library")
    build_service_operations(domain_root / "Service Operations")
    return output


def clean(output: Path) -> Path:
    output = output.resolve()
    if not output.exists():
        return output
    if not (output / MARKER).is_file():
        raise SystemExit(f"Refusing to remove unmarked directory: {output}")
    shutil.rmtree(output, onerror=remove_readonly)
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="directory to create")
    parser.add_argument("--clean", action="store_true", help="remove a marked generated estate instead of rebuilding it")
    arguments = parser.parse_args()
    result = clean(arguments.output) if arguments.clean else build(arguments.output)
    print(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
