"""kernel.md generation — the operative kernel from spec kernel blocks.

`build_kernel` is shared by `kernel` (generate / --check) and `coherence`
(drift check) so the two cannot disagree about what the kernel should contain.
"""

from __future__ import annotations

import datetime as dt
import re
import sys
from pathlib import Path

import yaml

from .model import parse_frontmatter
from .repo import git_short_sha

KERNEL_RE = re.compile(r"<!--\s*kernel\s*-->\s*\n(.*?)<!--\s*/kernel\s*-->", re.DOTALL)

KERNEL_HEADER = (
    "# Framework Operative Kernel\n\n"
    "Generated by `mdllm kernel` from the `<!-- kernel -->` blocks in the\n"
    "six operative (Tier 1) specs — the rules without the rationale. (The\n"
    "sentinel's `foundational_specs` catalog is wider: all 23 Tier 1+2 specs.)\n"
    "Load this at Tier 0\n"
    "instead of the full specs; load a full spec only when reasoning *about*\n"
    "the framework or when the kernel says to. Regenerate after any spec change.\n\n"
)


def _token_counter():
    try:
        import tiktoken
        enc = tiktoken.get_encoding("o200k_base")
        return lambda s: len(enc.encode(s))
    except ImportError:
        return lambda s: round(len(s) / 3.8)


def build_kernel(root: Path, specs: list[str], count) -> tuple[str, list[tuple], int, int]:
    """The deterministic kernel body (sans frontmatter) plus per-spec token
    detail. Shared by `kernel` (generate / --check) and `coherence` (drift
    check) so the two cannot disagree about what the kernel *should* contain —
    a single source for the very fact the drift check guards."""
    sections: list[str] = []
    detail: list[tuple] = []
    full_total = kernel_total = 0
    for name in specs:
        p = root / name
        if not p.exists():
            continue
        text = p.read_text(encoding="utf-8")
        full_total += count(text)
        blocks = KERNEL_RE.findall(text)
        if not blocks:
            continue
        body = "\n".join(b.strip() for b in blocks)
        kernel_total += count(body)
        sections.append(f"## {name}\n\n{body}\n")
        detail.append((name, count(body), count(text)))
    return KERNEL_HEADER + "\n".join(sections), detail, full_total, kernel_total


def cmd_kernel(args) -> int:
    """Generate kernel.md from <!-- kernel --> blocks in foundational specs."""
    root = Path(args.path).resolve()
    sentinel = root / ".markdownllm"
    if not sentinel.exists():
        sys.exit("mdllm: kernel requires a framework root (.markdownllm not found)")
    data = yaml.safe_load(sentinel.read_text(encoding="utf-8"))
    specs = data.get("foundational_specs") or []
    count = _token_counter()
    body, detail, full_total, kernel_total = build_kernel(root, specs, count)
    for name, kb, fb in detail:
        print(f"  {name:<40} {kb:>6,} / {fb:>6,} tokens")

    out = root / "kernel.md"

    if args.check:
        # Drift check: compare the deterministic body (frontmatter carries
        # timestamps/SHAs and is expected to differ between regenerations).
        if not out.exists():
            print("\nkernel.md missing — run `mdllm kernel` to generate it")
            return 1
        _, existing_body, _ = parse_frontmatter(out.read_text(encoding="utf-8"))
        if existing_body.strip() != body.strip():
            print("\nkernel: DRIFT — spec kernel blocks changed since kernel.md "
                  "was generated; run `mdllm kernel` and commit the result")
            return 1
        print("\nkernel: in sync")
        return 0

    content = (
        "---\n"
        "id: framework-kernel\n"
        "type: index\n"
        "status: live\n"
        "index_of: kernel\n"
        f"created: {dt.date.today().isoformat()}\n"
        f"generated: {dt.datetime.now().isoformat(timespec='seconds')}\n"
        f"generated_from: HEAD@{git_short_sha(root)}\n"
        f"coverage: {len(detail)}\n"
        f"framework_version: {data.get('version', 'unknown')}\n"
        "---\n\n"
        + body)
    out.write_text(content, encoding="utf-8")
    print(f"\nwrote kernel.md — {count(content):,} tokens "
          f"(kernel blocks {kernel_total:,} / full specs {full_total:,})")
    return 0
