"""Focused ports owned by Explorer use cases."""

from __future__ import annotations

from typing import Protocol

from markdownllm_explorer.core.models import (
    BoundaryToken, CollectionItem, CommitRecord, DocumentMode, DocumentRecord,
    EstateSnapshot, Page, RelativePath, RepositoryState, Source, SourceCounts,
    SourceSettingsRecord, TreeNode,
)


class SourceCatalogue(Protocol):
    def discover(self) -> EstateSnapshot: ...
    def source(self, source_id: str) -> Source: ...


class SourceBrowser(Protocol):
    def counts(self, token: BoundaryToken) -> SourceCounts: ...
    def tree(self, token: BoundaryToken, path: RelativePath, cursor: str | None) -> Page[TreeNode]: ...
    def search(self, token: BoundaryToken, query: str, cursor: str | None) -> Page[TreeNode]: ...
    def collection(self, token: BoundaryToken, kind: str, cursor: str | None) -> Page[CollectionItem]: ...
    def document(self, token: BoundaryToken, path: RelativePath, mode: DocumentMode) -> DocumentRecord: ...
    def settings(self, token: BoundaryToken) -> SourceSettingsRecord: ...


class CommitHistory(Protocol):
    def repository_state(self, token: BoundaryToken) -> RepositoryState: ...
    def commits(self, token: BoundaryToken, cursor: str | None) -> Page[CommitRecord]: ...

